"""
tools/builtin/shell.py

Shell execution tool (ROADMAP §7). Runs commands in the detected shell
(bash on Linux/macOS, PowerShell on Windows) through the sandbox module
(security/sandbox.py).

SANDBOX MODEL:
  Inert commands (read-only inspection from config.INERT_COMMANDS with
  no shell metacharacters) run via a lightweight subprocess — no Docker
  or fallback config needed. Non-inert commands go through Docker
  (strong isolation) or the explicit subprocess fallback (weak
  isolation, requires ALLOW_INSECURE_SANDBOX_FALLBACK=True).

APPROVAL MODEL:
  The shell tool uses a layered approval check:
  - If ToolApprovals.shell is True → always requires approval.
  - If the command is inert → auto-approved (light path).
  - If Docker is available → auto-approved (strong isolation).
  - If the fallback is used and AUTO_APPROVE_SANDBOX_FALLBACK is False
    → requires individual approval per run.

  TOCTOU safety: run() probes Docker once and passes the result to
  run_sandboxed(). If Docker was available during approval but is now
  down, and the fallback would have required approval, run() returns
  an error instead of silently downgrading.

FILE ACCESS:
  The sandbox restricts filesystem access to the workspace (Docker
  volume mount / fallback cwd). Output files generated by sandboxed
  commands appear in the workspace seamlessly.
"""

from __future__ import annotations

import logging

from pydantic import BaseModel, Field

import config
from security.sandbox import (
    SandboxUnavailable,
    _is_inert,
    detect_shell,
    is_docker_available,
    run_sandboxed,
)

logger = logging.getLogger(__name__)

# Compute the shell name once at import time to avoid blocking on
# subprocess probes every time the schema is accessed. On Windows this
# probes pwsh/powershell; a failure falls back to a static label.
try:
    _SHELL_DISPLAY = detect_shell()
except Exception:
    _SHELL_DISPLAY = "auto-detected"


# ---------------------------------------------------------------------------
# ---- Schema ---------------------------------------------------------------
# ---------------------------------------------------------------------------

class ShellParams(BaseModel):
    command: str = Field(
        ...,
        min_length=1,
        description=(
            "Shell command to execute. Interpreted by the detected shell "
            f"({_SHELL_DISPLAY}). Inert read-only commands (ls, cat, grep, "
            "etc.) run without full sandbox isolation. All other commands "
            "run inside a Docker container (or the explicit subprocess "
            "fallback)."
        ),
    )


TOOL_SCHEMA = {
    "name": "shell",
    "description": (
        "Execute a shell command in a sandboxed environment. "
        f"Shell: {_SHELL_DISPLAY}. "
        "Read-only inspection commands (ls, cat, grep, find, etc.) run "
        "with minimal overhead. All other commands run inside a Docker "
        "container with the workspace mounted at /workspace, or via the "
        "subprocess fallback if Docker is unavailable and explicitly "
        "enabled. Output is truncated at "
        f"{config.MAX_READ_CHARS} characters."
    ),
    "input_schema": ShellParams.model_json_schema(),
}


# ---------------------------------------------------------------------------
# ---- Approval check -------------------------------------------------------
# ---------------------------------------------------------------------------


def _shell_approval_check(tool_name: str, params: dict) -> bool:
    """Layered approval policy for the shell tool.

    1. Base config approval (ToolApprovals.shell) → always ask.
    2. Inert command → auto-approved (light path, no isolation concern).
    3. Docker available → auto-approved (strong isolation).
    4. Fallback + AUTO_APPROVE_SANDBOX_FALLBACK=False → ask per run.
    5. Fallback + AUTO_APPROVE_SANDBOX_FALLBACK=True → auto-approved.
    """
    approvals = config.ToolApprovals()
    if getattr(approvals, tool_name, False):
        return True

    command = params.get("command", "")

    if _is_inert(command):
        return False

    if is_docker_available():
        return False

    if config.ALLOW_INSECURE_SANDBOX_FALLBACK:
        return not config.AUTO_APPROVE_SANDBOX_FALLBACK

    return False


# ---------------------------------------------------------------------------
# ---- Tool handler ---------------------------------------------------------
# ---------------------------------------------------------------------------


def run(params: dict) -> dict:
    parsed = ShellParams(**params)

    # Probe Docker once for this execution — the result is threaded
    # into run_sandboxed to eliminate the TOCTOU gap where Docker
    # status changes between the approval check and execution.
    docker_up = is_docker_available()

    # TOCTOU safety net: if the approval check auto-approved because
    # Docker was available at that time, but Docker is now down and
    # we'd use the fallback, check whether the fallback would have
    # required approval that was never given.
    if not docker_up and not _is_inert(parsed.command):
        approvals = config.ToolApprovals()
        base_needs_approval = getattr(approvals, "shell", False)
        if (
            not base_needs_approval
            and config.ALLOW_INSECURE_SANDBOX_FALLBACK
            and not config.AUTO_APPROVE_SANDBOX_FALLBACK
        ):
            return {
                "error": (
                    "Docker became unavailable after the approval check. "
                    "The insecure subprocess fallback requires explicit "
                    "per-run approval (AUTO_APPROVE_SANDBOX_FALLBACK is "
                    "False). Please retry — the approval prompt will "
                    "appear this time."
                ),
            }

    try:
        return run_sandboxed(
            command=parsed.command,
            workspace_dir=config.WORKSPACE_DIR,
            docker_available=docker_up,
        )
    except SandboxUnavailable as e:
        return {"error": str(e)}
    except Exception as e:
        logger.exception("shell tool failed")
        return {"error": f"Shell execution failed: {e}"}
